name: tests

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        #- macos-latest
        #- windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    # rustup show will read the rust-toolchain file and automatically install
    - name: Setup rust
      run: rustup show

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
